### ISSUE TITLE
Not compatible with cordova-ios 6

### ISSUE THREAD

**Issue by dpogue** [microsoft/cordova-plugin-code-push#624]
### Description

The cordova-plugin-code-push plugin depends on the [deprecated (since 2017)](https://cordova.apache.org/blog/2017/10/18/from-filetransfer-to-xhr2.html) cordova-plugin-file-transfer plugin, which [is not compatible](https://github.com/apache/cordova-plugin-file-transfer/issues/258) with cordova-ios 6 and results in compiler issues.

The ideal solution here would be for cordova-plugin-code-push to handle the downloading, unzipping, and installation of app bundles in native code, that same way that [react-native-code-push](https://github.com/microsoft/react-native-code-push) does.

### Reproduction

Install cordova-plugin-code-push in an app built with cordova-ios 6.
There are compiler errors in the cordova-plugin-file-transfer Objective C files.

### Additional Information

* cordova-plugin-code-push version: 1.12.4
* List of installed plugins: cordova-plugin-code-push
* Cordova version: CLI 9.0.0 with cordova-ios@6.0.0
* iOS/Android/Windows version: iOS 13.5
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by davidellolio** [comment]
Hi,

I have the same error.

D.

**Comment by juanlurie** [comment]
I’m having the same problem. Juggling plugin versions for IOS with the WebKit restriction has led me to remove the cordova-plugin-file-transfer but that breaks code push

**Comment by sectionDayongtek** [comment]
Hi, I have the same problem. 

help plz...

**Comment by juanlurie** [comment]
I downgraded cordova-ios to 5.1.1 and added file transfer back and everything seems to be working now. The eco system is so fragile.

**Comment by jacobg** [comment]
Related to these issues #485 and #341. There's already a pull request #513 to remove file transfer, but Microsoft has neglected to merge it.

**Comment by swbradsh** [comment]
cordova-ios 6 also removed CDVUserAgentUtil, which this plugin is still referencing.

**Comment by bobrosoft** [comment]
`Use of undeclared identifier 'CDVUserAgentUtil'`
Switched to cordova-ios 5.1.1 because of that issue 🤦  https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/561

**Comment by videmort** [comment]
cordova-ios 6 is a major update those changes are a requirement by Apple. In order to remain compliant in their ecosystem. UIWebView is not allowed anymore. It's important to update this plugin.

**Comment by NickChowHK** [comment]
> `Use of undeclared identifier 'CDVUserAgentUtil'`
> Switched to cordova-ios 5.1.1 because of that issue 🤦 [ionic-team/cordova-plugin-ionic-webview#561](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/561)

@bobrosoft 
The cordova-ios 5.1.1 works well with code-push 1.12.0, but it will trigger the following issue if submitted to app store. May I know how you remove the UIWeivew from cordova-ios ios 5.1.1? Refer to this https://github.com/apache/cordova-ios/pull/773 ?

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability.

**Comment by bobrosoft** [comment]
@NickChowHK yes, solved by using:
 - "cordova-ios": "5.1.1",
 - "cordova-plugin-code-push": "1.12.0",
 - "cordova-plugin-ionic-webview": "5.0.0",

and adding next to `<platform name="ios">` section of the `config.xml`:
```
        <preference name="WKWebViewOnly" value="true" />
        <feature name="CDVWKWebViewEngine">
            <param name="ios-package" value="CDVWKWebViewEngine" />
        </feature>
        <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
```

**Comment by videmort** [comment]
@barryvdh yes with cordova-ios <6 this plugin works. The problem is that the apple ecosystem has changed and you will not be able to publish in the App Store with this plugin soon unless it is updated and guarantees compatibility with cordova-ios 6+.

With cordova-plugin-ionic-webview 5+ --> I think that you don't need this lines because only the WK engine is available now
```
<preference name="WKWebViewOnly" value="true" />
        <feature name="CDVWKWebViewEngine">
            <param name="ios-package" value="CDVWKWebViewEngine" />
        </feature>
        <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
```

**Comment by NickChowHK** [comment]
> @NickChowHK yes, solved by using:
> 
> * "cordova-ios": "5.1.1",
> * "cordova-plugin-code-push": "1.12.0",
> * "cordova-plugin-ionic-webview": "5.0.0",
> 
> and adding next to `<platform name="ios">` section of the `config.xml`:
> 
> ```
>         <preference name="WKWebViewOnly" value="true" />
>         <feature name="CDVWKWebViewEngine">
>             <param name="ios-package" value="CDVWKWebViewEngine" />
>         </feature>
>         <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
> ```

@bobrosoft 
That's what I tried before.....
however it still triggers the ITMS-90809: Deprecated API Usage when I submit the app yesterday. 

Apple rejected the app even the app is running on WKWebview as the UIWebview Code exists in the cordova-ios@5.1.1 and code-push@1.12

**Comment by bobrosoft** [comment]
@NickChowHK clean everything, delete `plugins` folder, `node_modules` etc, everything temporary, `rm -rf ~/Library/Developer/Xcode/DerivedData` etc, ensure correct plugin version installed, check installed versions manually, set `<plugin name="cordova-plugin-ionic-webview" spec="^5.0.0" />` in `config.xml` just in case (but I don't think it matters). I was able to push app without that warning, so, solved for me.

**Comment by bobrosoft** [comment]
@NickChowHK other solution will be to drop code-push and use latest cordova-ios.

**Comment by swbradsh** [comment]
@NickChowHK You need to be on at least version **1.12.1** of this plugin to fix the WKWebView issue.

**Comment by bobrosoft** [comment]
@NickChowHK yes, I double-checked now, I actually have cordova-plugin-code-push version 1.12.5 installed, not 1.12.0. Sorry for misinform.

**Comment by ermik** [comment]
Working iOS and Android with defaults platform versions.

```
Ionic:

   Ionic CLI                     : 6.10.1 (/Users/ludufre/.npm-packages/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.901.11
   @angular-devkit/schematics    : 9.1.11
   @angular/cli                  : 9.1.11
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 9 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Users/ludufre/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.18.1 (/usr/local/bin/node)
   npm               : 6.14.5
   OS                : macOS
   Xcode             : Xcode 11.6 Build version 11E708
```

With `cordova-ios@6.1.0` get error with deprecated `CDVUserAgentUtil`:

![image](https://user-images.githubusercontent.com/4112077/87878638-f41f9800-c9bb-11ea-8d7c-e62896dd3c55.png)

I didn't find any code that `[CDVUserAgentUtil ...acquireLock]` so I commented that line and compiled and worked perfectly in 6.1.1.

I made that small change, here it is: https://github.com/ludufre/cordova-plugin-code-push/commit/159e18cfa9e2aa0c5c6d47ca7b3f0e1d2b1c9f1e (I new on this Github thing, so I don't know how to send this change to this Pull Request / Or @ermik can do this change himself)

_Originally posted by @ludufre in https://github.com/microsoft/cordova-plugin-code-push/pull/513#issuecomment-660669212_

**Comment by videmort** [comment]
@ermik  is not a valid solution, cordova file transfer plugin is deprecated and must be removed in this plugin. 
In resume is not valid if you want to upload to marked.

**Comment by ermik** [comment]
> Originally posted by @ludufre in[ #513 (comment)](https://github.com/microsoft/cordova-plugin-code-push/pull/513#issuecomment-660669212)

@videmort As you can see at the bottom of my comment, I'm just reposting the relevant information which was provided by @ludufre in #513, so that it does not get unnoticed.

**Comment by videmort** [comment]
@ermik  👍

**Comment by alexandergoncharov** [comment]
Hi all,

We merged https://github.com/microsoft/cordova-plugin-code-push/pull/513 and publish a new version: https://github.com/microsoft/cordova-plugin-code-push/releases/tag/v1.13.0

It should fix supporting `cordova-ios@6`. Could you please test it and let me know your results?

**Comment by NickChowHK** [comment]
> Hi all,
> 
> We merged #513 and publish a new version: https://github.com/microsoft/cordova-plugin-code-push/releases/tag/v1.13.0
> 
> It should fix supporting `cordova-ios@6`
> Could you please test it and let me know your results?

The app still showed a blank screen after a new update installation,  here is my package; 
"dependencies": {
    "code-push": "3.0.1",
    "cordova": "9.0.0",
    "cordova-ios": "^6.1.0",
    "cordova-plugin-add-swift-support": "^2.0.2",
    "cordova-plugin-advanced-http": "3.0.0",
    "cordova-plugin-app-preferences": "^0.99.3",
    "cordova-plugin-buildinfo": "4.0.0",
    "cordova-plugin-code-push": "1.13.0",
    "cordova-plugin-exclude-files": "^1.0.1",
    "cordova-plugin-file": "6.0.2",
    "cordova-plugin-keyboard": "^1.2.0",
    "cordova-plugin-media": "5.0.3",
    "cordova-plugin-qrscanner": "^3.0.1",
    "cordova-plugin-screen-orientation": "3.0.2",
    "cordova-plugin-settings-hook": "^0.3.1",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova-plugin-zip": "3.1.0",
    "cordova-sqlite-storage": "5.0.1"
  }

I am no idea how to file the problem.....no error message in the console

**Comment by szh** [comment]
Thanks guys for pushing a new version!
I'm unfortunately still having the same results as @NickChowHK

**Comment by videmort** [comment]
@alexandergoncharov I tried to archive running cordova build ios --device but fails.

**Comment by szh** [comment]
@videmort Is that new with my PR? What error do you get?

**Comment by sithwarrior** [comment]
@szh it works on my build setup.

**Comment by videmort** [comment]
@szh Sorry for the delay! --> In my setup is not working :(

**Comment by videmort** [comment]
@alexandergoncharov  In white proyect fails the building (last cordova CLI and cordova-ios platform)

**Comment by nicholaszuccarelli** [comment]
Hey guys, I'm thinking of using this plugin for my Cordova app, but don't want to start until I know for sure that it is compatible with the latest Cordova packages (cordova-ios, cordova-android, cordova 10.0).

Has this problem with the iOS package been resolved?

**Comment by NickChowHK** [comment]
> Hey guys, I'm thinking of using this plugin for my Cordova app, but don't want to start until I know for sure that it is compatible with the latest Cordova packages (cordova-ios, cordova-android, cordova 10.0).
> 
> Has this problem with the iOS package been resolved?

Not yet resolved. I recommend not to use this plugin unless your app is using it already.

**Comment by nicholaszuccarelli** [comment]
Thanks. We will hold off from implementing it then until its compatible.

**Comment by Krasavinigor** [comment]
Hi there! 
Unfortunately, I couldn't reproduce this issue. Could you please provide (or/and)
* repro steps
* demo project

my dependencies: 
"cordova-ios": "^6.1.0",
"cordova-plugin-advanced-http": "^3.0.1",
"cordova-plugin-code-push": "^1.13.0"

**Comment by pitAlex** [comment]
With 1.13.0 the download progress callback is no longer firing. This is for both Android and iOS.

**Comment by Krasavinigor** [comment]
Hi there! 
We opened PR for fixing the issue with **CDVUserAgentUtil**: https://github.com/microsoft/cordova-plugin-code-push/pull/642
Take a look if you have time.
@bobrosoft, Could you please let me know if it was helpful for you?

**Comment by bobrosoft** [comment]
@Krasavinigor hi, sorry, can't touch that fragile thing atm or our PM will shoot me down if I will not deliver 😅🙈

**Comment by alexandergoncharov** [comment]
Hi all,
We merged this PR https://github.com/microsoft/cordova-plugin-code-push/pull/642 and published new `1.13.1` version. Could you please test it and let us know if it fixed your issue?

**Comment by daisito** [comment]
With cordova-ios 5.1.5 resolved me problem

**Comment by pitAlex** [comment]
> With cordova-ios 5.1.1 resolved me problem

You cannot use less than cordova ios 6. Apple will reject any new package still referencing UIWebView.

**Comment by daisito** [comment]
> > With cordova-ios 5.1.1 resolved me problem
> 
> 
> 
> You cannot use less than cordova ios 6. Apple will reject any new package still referencing UIWebView.

But Cordova iOS 6 is problem with code push of appcenter!!
Any solutions?

**Comment by pitAlex** [comment]
Most are in the same position. Because of Apple requirements, there really isn't anything to do but either wait for the owners of this plugin to make the updates or do them yourself. In our case, the plugin works as we only use the code-push cli, version 2.1.9.

**Comment by alexandergoncharov** [comment]
Hi all,

If you still have issues could you please provide some demo app with reproducing issue and reprosteps?
Unfortunately, we can't reproduce any issues with it.

**Comment by sithwarrior** [comment]
Hi @alexandergoncharov Im experiencing the same issue with this version.

App updates using codepush results in a white page.
Debugging using Safari, shows that the index.html of the new package returns a 404

`URL: app://localhost/Users/psykes/Library/Developer/CoreSimulator/Devices/635EC000-85A2-4174-B410-C87EDB6D18FA/data/Containers/Data/Application/3B86386E-DF1C-4855-BC9F-CC8C0729E186/Library/NoCloud/codepush/deploy/versions/b8affdc4e310826555cb3300e112d53caa8bef1db87c2bc53c4ba7fcf217e9ff/www/index.html
Status: 404
Source: —`

It could seem like this plugin doesnt handle the new Url Scheme of Cordova IOS 6+ app://localhost ?

**UIWebView**
Additionally, the plugin still contains code referencing UIWebView 
`[(UIWebView*)self.webView loadRequest:[NSURLRequest requestWithURL:url]];`

This would prevent any new app built with this plugin to be submitted to the App Store, and any app update with this plugin, would get a warning, and not be possible by December. Info from Apple [https://developer.apple.com/news/?id=12232019b](url)

**Comment by sithwarrior** [comment]
@alexandergoncharov I just tested using the included Sample Apps in this project [https://github.com/microsoft/cordova-plugin-code-push/tree/master/samples](url)

If you use the new recommended Url Scheme of Cordova iOS 6
`<preference name="scheme" value="app" />
<preference name="hostname" value="localhost" />`

This results in a 401, after an app update.

The new Url Scheme is recommended to avoid CORS restrictions, hosting your ios app from file://
[https://cordova.apache.org/announcements/2020/06/01/cordova-ios-release-6.0.0.html](url)

> Additionaly, WKURLSchemeHandler support has been introduced with this release. Using a custom scheme to serve your app content through fixes CORS issues that exist because of the strict security policies that WKWebView has applied to the file scheme. You can easily configure your Cordova project to use a custom scheme by setting the preference options scheme and hostname in the config.xml file.

<preference name="scheme" value="app" />
<preference name="hostname" value="localhost" />

**Comment by pitAlex** [comment]
> [(UIWebView*)self.webView loadRequest:[NSURLRequest requestWithURL:url]];

I can confirm it does show warning upon uploading to iTunes. You can't check if the class exists and you can't have it like that either. There must be no "UIWebView" mentioned in code. I personally removed the lines and did not see anything break yet.

**Comment by Krasavinigor** [comment]
Hi @pitAlex! 
We know that UIWebView is deprecated. We are going to remove all usage of UIWebView soon.

**Comment by mden-crf** [comment]
> With 1.13.0 the download progress callback is no longer firing. This is for both Android and iOS.

Hello, does anybody has a workaround to have the download progress callback with 1.13.x? As @pitAlex mentionned before, it is no longer firing. Seems linked to #652 too.

**Comment by mark-divitt** [comment]
Hi Folks, where are we with this issue?  iOS 14 is released that requires WKWebView.  Sure seems to me like this would be a #1 priority to get fixed as CodePush for Cordova (on iOS) is completely broken as this point.  Any activity on this?

**Comment by ruslan-bikkinin** [comment]
Hi everyone and deeply sorry for such a delayed response. The team was highly underresourced and couldn't take care of this immediately.
Anyway, here's the PR for fixing this #655. We would appreciate any other 👀  from the community on it.

**Comment by ruslan-bikkinin** [comment]
The new version that fixes the problems with WKWebView for cordova-ios@6 just has been released: [v2.0.0](https://github.com/microsoft/cordova-plugin-code-push/releases/tag/v2.0.0). Also, in this version support for UIWebView is dropped as well. 
I'm going to close this issue so **if you have any other problems with cordova-ios 6 on 2.0.0 version of the plugin, please create another one**.
