### ISSUE TITLE
Cordova FileTransfer/FileUtils Error

### ISSUE THREAD

**Issue by brassier** [Microsoft/cordova-plugin-code-push#320]
### Description

After installing the code-push cordova plugin I can no longer build my android app.  Getting errors on items that CodePush depends on (File/File Transfer).  Not sure if this is a dependency or cordova version issue?

### Additional Information

* cordova-plugin-code-push version:  
1.10.0-beta
* List of installed plugins:
code-push 2.0.2-beta "CodePushAcquisition"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-code-push 1.10.0-beta "CodePush"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-safariviewcontroller 1.4.7 "SafariViewController"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
* Cordova version: 6.5
* iOS/Android/Windows version:
    Android SDK Tools : 25.2.5
    Node              : v6.11.1
    npm               : 3.10.10
    OS                : Windows 10
* Does this reproduce on a debug build or release build? 
Debug and Release

I'm getting the error below.  I've tried downgrading code-push to a version that works on a different app I've made.

        C:\dev\platforms\android\src\org\apache\cordova\filetransfer\FileTransfer.java:49: error:
        package org.apache.cordova.file does not exist
        import org.apache.cordova.file.FileUtils;
                                       ^
        
  
      C:\dev\platforms\android\src\org\apache\cordova\filetransfer\FileTransfer.java:851: error:
        cannot find symbol
                                 FileUtils filePlugin = (FileUtils) pm.getPlugin("File");
                                 ^
           symbol: class FileUtils
        
  
      C:\dev\platforms\android\src\org\apache\cordova\filetransfer\FileTransfer.java:851: error:
        cannot find symbol
                                 FileUtils filePlugin = (FileUtils) pm.getPlugin("File");
                                                         ^
           symbol: class FileUtils
        Note: Some input files use or override a deprecated API.
        Note: Recompile with -Xlint:deprecation for details.
        Note: Some input files use unchecked or unsafe operations.
        Note: Recompile with -Xlint:unchecked for details.
        3 errors
        :compileDebugJavaWithJavac FAILED

**Comment by brassier** [comment]
More info on this one.  I have a different app that does work with code-push.  I had to do a bunch of hoop-jumping to get my new app to use the same plugin versions as my old app, but then finally I got past this error.  Seems I had to pull in: `cordova-plugin-file 4.3.2`, and then `cordova-plugin-code-push 1.9.3-beta`.  That combination seems to build at least.

Not sure if this issue is specific to cordova 6.5.0, or possibly cordova-android 6.1.2?

**Comment by Zavorotyuk** [comment]
Have the same problem. I use PhoneGap build.
PhoneGap cli version 7.0.1. 
Set cordova-plugin-code-push version to 1.9.3-beta and cordova-plugin-file to 4.3.2 but it didn't help.

**Comment by brassier** [comment]
The hoops I had to jump through to get it to work with 1.9.3-beta involved:

- uninstall code push plugin
- uninstall file & file-transfer plugins
- update my cordova-android platform to 6.3.0
- install file 4.3.2
- install code-push 1.9.3-beta
- remove & re-add Android platform

**Comment by Zavorotyuk** [comment]
Unfortunately, I can not update the version of android as the latest version of PhonegapBuild cli uses  android 6.2.3

**Comment by brassier** [comment]
@ruslan-bikkinin  - Can you help us understand what's happening here?  Any idea why it seems to be so difficult to get a version of cordova code-push installed recently?

**Comment by ruslan-bikkinin** [comment]
Hi @brassier 

I tried to reproduce your issue and i was able to get error you are describing **without** cordova-plugin-code-push been installed. I've been created empty application with plugins list you've been provided.

<details>
 <summary>Details</summary>

```console
rbikkinin@rbikkinin-work:/media/rbikkinin/work/support/cordova-issue320/app$ cordova --version
6.5.0
rbikkinin@rbikkinin-work:/media/rbikkinin/work/support/cordova-issue320/app$ cordova plugins
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-safariviewcontroller 1.4.7 "SafariViewController"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
rbikkinin@rbikkinin-work:/media/rbikkinin/work/support/cordova-issue320/app$ cordova buildDiscovered plugin "cordova-plugin-customurlscheme" in config.xml. Adding it to the project
Fetching plugin "cordova-plugin-customurlscheme@4.3.0" via npm
Failed to restore plugin "cordova-plugin-customurlscheme" from config.xml. You might need to try adding it again. Error: Variable(s) missing (use: --variable URL_SCHEME=value).
ANDROID_HOME=/work/sdk
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
Subproject Path: CordovaLib
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint UP-TO-DATE
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders UP-TO-DATE
:CordovaLib:compileDebugShaders UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
:CordovaLib:mergeDebugJniLibFolders UP-TO-DATE
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders UP-TO-DATE
:CordovaLib:compileReleaseShaders UP-TO-DATE
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript UP-TO-DATE
:CordovaLib:generateReleaseResValues UP-TO-DATE
:CordovaLib:generateReleaseResources UP-TO-DATE
:CordovaLib:packageReleaseResources UP-TO-DATE
:CordovaLib:processReleaseManifest UP-TO-DATE
:CordovaLib:generateReleaseBuildConfig UP-TO-DATE
:CordovaLib:processReleaseResources UP-TO-DATE
:CordovaLib:generateReleaseSources UP-TO-DATE
:CordovaLib:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:CordovaLib:compileReleaseJavaWithJavac UP-TO-DATE
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:CordovaLib:mergeReleaseJniLibFolders UP-TO-DATE
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:CordovaLib:bundleRelease UP-TO-DATE
:prepareComAndroidSupportCustomtabs2320Library UP-TO-DATE
:prepareComAndroidSupportSupportV42320Library UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:compileDebugJavaWithJavac
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/media/rbikkinin/work/support/cordova-issue320/app/platforms/android/src/org/apache/cordova/filetransfer/FileTransfer.java:49: error: package org.apache.cordova.file does not exist
import org.apache.cordova.file.FileUtils;
                              ^
/media/rbikkinin/work/support/cordova-issue320/app/platforms/android/src/org/apache/cordova/filetransfer/FileTransfer.java:851: error: cannot find symbol
                        FileUtils filePlugin = (FileUtils) pm.getPlugin("File");
                        ^
  symbol: class FileUtils
/media/rbikkinin/work/support/cordova-issue320/app/platforms/android/src/org/apache/cordova/filetransfer/FileTransfer.java:851: error: cannot find symbol
                        FileUtils filePlugin = (FileUtils) pm.getPlugin("File");
                                                ^
  symbol: class FileUtils
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /media/rbikkinin/work/support/cordova-issue320/app/platforms/android/src/org/apache/cordova/filetransfer/FileTransfer.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.476 secs
Error: /media/rbikkinin/work/support/cordova-issue320/app/platforms/android/gradlew: Command failed with exit code 1 Error output:
/media/rbikkinin/work/support/cordova-issue320/app/platforms/android/src/org/apache/cordova/filetransfer/FileTransfer.java:49: error: package org.apache.cordova.file does not exist
import org.apache.cordova.file.FileUtils;
                              ^
/media/rbikkinin/work/support/cordova-issue320/app/platforms/android/src/org/apache/cordova/filetransfer/FileTransfer.java:851: error: cannot find symbol
                        FileUtils filePlugin = (FileUtils) pm.getPlugin("File");
                        ^
  symbol: class FileUtils
/media/rbikkinin/work/support/cordova-issue320/app/platforms/android/src/org/apache/cordova/filetransfer/FileTransfer.java:851: error: cannot find symbol
                        FileUtils filePlugin = (FileUtils) pm.getPlugin("File");
                                                ^
  symbol: class FileUtils
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /media/rbikkinin/work/support/cordova-issue320/app/platforms/android/src/org/apache/cordova/filetransfer/FileTransfer.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

</details>


Please try to update cordova cli to latest version (`7.1.0`), reinstall all plugins and, possible, readd platform (be careful when you are doing that - you will loss any native side code of application on your local machine) and then try to build your application.

Please let us know if it help you.

**Comment by ruslan-bikkinin** [comment]
Yes, it seems to be latest cordova file & file-transfer plugins are incompatible with cordova-android@6.1.2 which is default version cordova-cli@6.5.0 used. So, I believe update to 6.3.0 will solve your problem @brassier.

**Comment by ruslan-bikkinin** [comment]
@Zavorotyuk could you please submit separate issue for your problem? We could continue to discuss it there.

**Comment by Zavorotyuk** [comment]
@ruslan-bikkinin Submited #322

**Comment by brassier** [comment]
@ruslan-bikkinin - confirmed.  Thanks for nailing that down!

**Comment by junerockwell** [comment]
Had the exact same problem. I had to install cordova android@7.0.0. I can build successfully and run on a real Android device. Thanks @ruslan-bikkinin
